<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CatalogProductsSeeder extends Seeder
{
    /**
     * Seed 24 products from Simple Cake Shop catalog.
     * Run with: php artisan db:seed --class=CatalogProductsSeeder
     */
    public function run(): void
    {
        // Get existing product names to avoid duplicates
        $existingNames = DB::table('products')->pluck('name')->map(fn($n) => strtolower($n))->toArray();

        $now = now();

        $products = [
            [
                'id'             => 'fqh2ctwx4i',
                'name'           => 'Mini Duo Drip Cake',
                'description'    => 'Adorable mini cakes with smooth buttercream finish, chocolate drip, and piped rosette crown. Available in Lemon and Vanilla flavors. Perfect for small celebrations and intimate gatherings.',
                'price'          => 650.0,
                'image_path'     => '/storage/uploads/products/20260414105849_c7cfa486f040.jpg',
                'classification' => 'Standard',
                'flavor'         => 'Lemon / Vanilla',
                'is_available'   => 1,
                'max_per_day'    => 0,
                'created_at'     => $now,
            ],
            [
                'id'             => 'wql3wevv4d',
                'name'           => 'Cheesy Heaven Cake',
                'description'    => 'Rich and indulgent cake generously topped with freshly grated cheese — sweet, salty, and absolutely irresistible. A Filipino classic that everyone loves.',
                'price'          => 800.0,
                'image_path'     => '/storage/uploads/products/20260414105849_5afbd9b88327.jpg',
                'classification' => 'Standard',
                'flavor'         => 'Cheese',
                'is_available'   => 1,
                'max_per_day'    => 0,
                'created_at'     => $now,
            ],
            [
                'id'             => 'rnys5rrm3t',
                'name'           => 'Blue Velvet Rosette Cake',
                'description'    => 'Elegant sky-blue buttercream cake adorned with beautiful rosette piping and gold pearl accents. Chocolate drip sides add a luxurious touch. Great for baby showers and birthdays.',
                'price'          => 950.0,
                'image_path'     => '/storage/uploads/products/20260414105849_241d8c0c788e.jpg',
                'classification' => 'Standard',
                'flavor'         => 'Vanilla',
                'is_available'   => 1,
                'max_per_day'    => 0,
                'created_at'     => $now,
            ],
            [
                'id'             => '2x3ytnmp8v',
                'name'           => 'Caramel Oreo Drip Cake',
                'description'    => 'Decadent yellow buttercream cake topped with caramel glaze, whole Oreo cookies, and crunchy walnut bits. Rich chocolate drip sides make this a showstopper for any celebration.',
                'price'          => 1100.0,
                'image_path'     => '/storage/uploads/products/20260414105849_21aa4a9976dd.jpg',
                'classification' => 'Standard',
                'flavor'         => 'Caramel',
                'is_available'   => 1,
                'max_per_day'    => 0,
                'created_at'     => $now,
            ],
            [
                'id'             => 'jm1cmvig94',
                'name'           => 'Mr & Mrs Wedding Cake',
                'description'    => 'Stunning two-tier wedding cake featuring a teal fondant base layer with gold leaf accents, white roses, and an elegant white top tier. Comes with a gold Mr & Mrs acrylic topper.',
                'price'          => 3500.0,
                'image_path'     => '/storage/uploads/products/20260414105849_3b2a26e47e61.jpg',
                'classification' => 'Fondant',
                'flavor'         => 'Vanilla',
                'is_available'   => 1,
                'max_per_day'    => 0,
                'created_at'     => $now,
            ],
            [
                'id'             => '2gsokgi8dj',
                'name'           => 'Blueberry Dream Cake',
                'description'    => 'Vibrant teal-blue buttercream cake with piped shell border and rich blueberry compote center. A refreshing treat bursting with real blueberry flavor in every bite.',
                'price'          => 900.0,
                'image_path'     => '/storage/uploads/products/20260414105850_6ab2b660fa73.jpg',
                'classification' => 'Standard',
                'flavor'         => 'Blueberry',
                'is_available'   => 1,
                'max_per_day'    => 0,
                'created_at'     => $now,
            ],
            [
                'id'             => '7kkdmc4lo3',
                'name'           => 'Mango Cream Cake',
                'description'    => 'Classic yellow buttercream cake with a generous pool of sweet mango jam at the center, piped rosette border, and chocolate drip sides. A Filipino favorite bursting with tropical flavor.',
                'price'          => 950.0,
                'image_path'     => '/storage/uploads/products/20260414105850_5d2503854f31.jpg',
                'classification' => 'Standard',
                'flavor'         => 'Mango',
                'is_available'   => 1,
                'max_per_day'    => 0,
                'created_at'     => $now,
            ],
            [
                'id'             => '6m7nj19vky',
                'name'           => 'Blue Berry Swirl Cake',
                'description'    => 'Light blue buttercream cake with swirled rosette piping and a luscious dark blueberry compote topping. Colorful rainbow sprinkles add a festive touch. Perfect for any party.',
                'price'          => 900.0,
                'image_path'     => '/storage/uploads/products/20260414105850_cb22e90d4cac.jpg',
                'classification' => 'Standard',
                'flavor'         => 'Blueberry',
                'is_available'   => 1,
                'max_per_day'    => 0,
                'created_at'     => $now,
            ],
            [
                'id'             => '9rmc04gtx4',
                'name'           => 'Mango Caramel Cake',
                'description'    => 'Smooth yellow buttercream cake topped with a glossy mango-caramel sauce, shell-piped border, and elegant chocolate drip. Rich tropical sweetness in every slice.',
                'price'          => 950.0,
                'image_path'     => '/storage/uploads/products/20260414105850_aa45efb1a62a.jpg',
                'classification' => 'Standard',
                'flavor'         => 'Mango',
                'is_available'   => 1,
                'max_per_day'    => 0,
                'created_at'     => $now,
            ],
            [
                'id'             => 'ruqrh8udxn',
                'name'           => 'Cookies and Cream Cake',
                'description'    => 'Creamy white cake coated in Oreo crumble base, topped with cookies and cream buttercream rosettes and chunks of white chocolate. A cookies and cream lover\'\'s dream.',
                'price'          => 1050.0,
                'image_path'     => '/storage/uploads/products/20260414105850_7f5bb7f3559c.jpg',
                'classification' => 'Standard',
                'flavor'         => 'Cookies & Cream',
                'is_available'   => 1,
                'max_per_day'    => 0,
                'created_at'     => $now,
            ],
            [
                'id'             => '6evp7e32g2',
                'name'           => 'Mocha Chocolate Drip Cake',
                'description'    => 'Rich mocha buttercream cake with chocolate drip sides and festive rainbow sprinkles. Deeply flavored with coffee and chocolate — perfect for coffee lovers and celebrations alike.',
                'price'          => 950.0,
                'image_path'     => '/storage/uploads/products/20260414105850_fe5abffab5b9.jpg',
                'classification' => 'Standard',
                'flavor'         => 'Mocha',
                'is_available'   => 1,
                'max_per_day'    => 0,
                'created_at'     => $now,
            ],
            [
                'id'             => '3uf8ox3ma0',
                'name'           => 'Naruto Theme Cake',
                'description'    => 'Eye-catching themed birthday cake featuring Naruto Uzumaki illustration on a golden yellow fondant base. Complete with flame toppers and a number topper — perfect for anime fans.',
                'price'          => 1800.0,
                'image_path'     => '/storage/uploads/products/20260414105850_63e628d0dc7b.jpg',
                'classification' => 'Fondant',
                'flavor'         => 'Vanilla',
                'is_available'   => 1,
                'max_per_day'    => 0,
                'created_at'     => $now,
            ],
            [
                'id'             => 'ssrpff1nxc',
                'name'           => 'Malteser Cream Cake',
                'description'    => 'Classic white buttercream cake decorated with Maltesers chocolate balls, swirled rosette piping, and elegant chocolate drip lines. Sweet, crunchy, and absolutely delightful.',
                'price'          => 1000.0,
                'image_path'     => '/storage/uploads/products/20260414105850_19cb9f0cdca7.jpg',
                'classification' => 'Standard',
                'flavor'         => 'Chocolate',
                'is_available'   => 1,
                'max_per_day'    => 0,
                'created_at'     => $now,
            ],
            [
                'id'             => 'm86jl3wqmm',
                'name'           => 'Dark Chocolate Matcha Cake',
                'description'    => 'Indulgent dark chocolate glazed cake with striking matcha green drizzle. Available as a layered naked cake or fully glazed style. Bold flavors for the adventurous cake lover.',
                'price'          => 1100.0,
                'image_path'     => '/storage/uploads/products/20260414105850_52e136ac2d1b.jpg',
                'classification' => 'Standard',
                'flavor'         => 'Dark Chocolate',
                'is_available'   => 1,
                'max_per_day'    => 0,
                'created_at'     => $now,
            ],
            [
                'id'             => '9gqmp3areh',
                'name'           => 'Butterfly Cupcake Set',
                'description'    => 'Adorable chocolate cupcakes with lavender-purple buttercream swirls and butterfly fondant toppers. Perfect for birthdays, baby showers, and garden parties. Sold per dozen.',
                'price'          => 480.0,
                'image_path'     => '/storage/uploads/products/20260414105850_e957b92c6171.jpg',
                'classification' => 'Standard',
                'flavor'         => 'Chocolate',
                'is_available'   => 1,
                'max_per_day'    => 0,
                'created_at'     => $now,
            ],
            [
                'id'             => 'l3xi67kwg1',
                'name'           => 'Classic White Cream Cake',
                'description'    => 'Elegant all-white buttercream cake with delicate rosette piping border, gold pearl accents, and chocolate drip. Clean, sophisticated, and perfect for any occasion.',
                'price'          => 900.0,
                'image_path'     => '/storage/uploads/products/20260414105850_7c64dcbf26e7.jpg',
                'classification' => 'Standard',
                'flavor'         => 'Vanilla',
                'is_available'   => 1,
                'max_per_day'    => 0,
                'created_at'     => $now,
            ],
            [
                'id'             => 'tlafgdlopk',
                'name'           => 'Mocha Truffle Cake',
                'description'    => 'Smooth mocha cream cake topped with Maltesers, chocolate wafer sticks, and Hershey kisses. Chocolate drip border adds indulgence to this irresistible mocha creation.',
                'price'          => 1050.0,
                'image_path'     => '/storage/uploads/products/20260414105851_655e51a9ce8f.jpg',
                'classification' => 'Standard',
                'flavor'         => 'Mocha',
                'is_available'   => 1,
                'max_per_day'    => 0,
                'created_at'     => $now,
            ],
            [
                'id'             => '7i4f8cf1c4',
                'name'           => 'Mocha Rosette Drip Cake',
                'description'    => 'Beautiful mocha buttercream cake with lush rosette piping all around the top edge, festive sprinkles, and generous chocolate drip. A classic celebration cake with bold coffee-chocolate flavor.',
                'price'          => 1000.0,
                'image_path'     => '/storage/uploads/products/20260414105851_0373ae24bcfd.jpg',
                'classification' => 'Standard',
                'flavor'         => 'Mocha',
                'is_available'   => 1,
                'max_per_day'    => 0,
                'created_at'     => $now,
            ],
            [
                'id'             => 'i51cqync4n',
                'name'           => 'Blush White Drip Cake',
                'description'    => 'Romantic blush-white buttercream cake with elegant rosette border, gold pearl sprinkles, and chocolate drip. Light and graceful — ideal for weddings, anniversaries, and special occasions.',
                'price'          => 950.0,
                'image_path'     => '/storage/uploads/products/20260414105851_d78affe7275f.jpg',
                'classification' => 'Standard',
                'flavor'         => 'Vanilla',
                'is_available'   => 1,
                'max_per_day'    => 0,
                'created_at'     => $now,
            ],
            [
                'id'             => '1qnqe9629h',
                'name'           => 'Double Tier Chocolate Cake',
                'description'    => 'Impressive two-tier all-chocolate buttercream cake with intricate textured piping on the bottom tier and elegant swirl piping on top. A grand centerpiece for milestone celebrations.',
                'price'          => 2800.0,
                'image_path'     => '/storage/uploads/products/20260414105851_1af75b5458ff.jpg',
                'classification' => 'Standard',
                'flavor'         => 'Chocolate',
                'is_available'   => 1,
                'max_per_day'    => 0,
                'created_at'     => $now,
            ],
            [
                'id'             => 'f80l098v07',
                'name'           => 'Pure White Drip Cake',
                'description'    => 'Pristine white buttercream cake with soft rosette border, gold pearl accents, and chocolate drip. Simple, elegant, and beautiful — perfect for any celebration that deserves a classic touch.',
                'price'          => 900.0,
                'image_path'     => '/storage/uploads/products/20260414105851_d7697c6396bf.jpg',
                'classification' => 'Standard',
                'flavor'         => 'Vanilla',
                'is_available'   => 1,
                'max_per_day'    => 0,
                'created_at'     => $now,
            ],
            [
                'id'             => '261sbb0e27',
                'name'           => 'Oreo Cream Mini Cake',
                'description'    => 'Compact yet decadent cookies and cream cake with Oreo crumble base, cream cheese-style buttercream, white chocolate shard toppers, and dark Oreo crumble center. Rich in every bite.',
                'price'          => 850.0,
                'image_path'     => '/storage/uploads/products/20260414105851_714c862fcc4e.jpg',
                'classification' => 'Standard',
                'flavor'         => 'Cookies & Cream',
                'is_available'   => 1,
                'max_per_day'    => 0,
                'created_at'     => $now,
            ],
            [
                'id'             => 'e60zuye8xl',
                'name'           => 'Hello Kitty Birthday Cake',
                'description'    => 'Whimsical Hello Kitty themed birthday cake with pink ruffled buttercream, Hello Kitty figurines, and personalized topper. A dream cake for every Hello Kitty fan young and old.',
                'price'          => 1800.0,
                'image_path'     => '/storage/uploads/products/20260414105851_df781209a412.jpg',
                'classification' => 'Fondant',
                'flavor'         => 'Strawberry',
                'is_available'   => 1,
                'max_per_day'    => 0,
                'created_at'     => $now,
            ],
            [
                'id'             => 'ybjo8z9vp9',
                'name'           => 'Mango Delight Cake',
                'description'    => 'Bright yellow buttercream cake with piped rosette border, sweet mango jam center, and chocolate drip sides. A tropical treat that captures the irresistible flavor of ripe Philippine mangoes.',
                'price'          => 950.0,
                'image_path'     => '/storage/uploads/products/20260414105851_2b58a6ae3ab7.jpg',
                'classification' => 'Standard',
                'flavor'         => 'Mango',
                'is_available'   => 1,
                'max_per_day'    => 0,
                'created_at'     => $now,
            ],
        ];

        // Filter out products that already exist by name
        $toInsert = array_filter($products, function($p) use ($existingNames) {
            return !in_array(strtolower($p['name']), $existingNames);
        });

        if (empty($toInsert)) {
            $this->command->info('All catalog products already exist — nothing to add.');
            return;
        }

        DB::table('products')->insert(array_values($toInsert));

        $this->command->info('✅ ' . count($toInsert) . ' new cake products added! (' . (count($products) - count($toInsert)) . ' skipped — already exist)');
    }
}
